### ISSUE TITLE
Allow the use of `.tres` in addition to `.material`

### ISSUE THREAD

**Issue by RomualdDub** [codecat/godot-tbloader#15]
Hello !
It would be cool if materials (.tres) will be loaded instead of image files (.png).
Like Qodot does.
It's useful, for example, with Material Maker. When the "albedo" have the same name of the Material file.
I coded a script which can be attached to the TBLoader node, in your Godot project... Just for testing purpose :
https://pastebin.com/uXdSgYYm

**Comment by codecat** [comment]
If your material is saved with the extension `.material` (not `.tres`) it will use the material as per #12. I have been thinking about supporting `.tres` with this too though, because it is the default in Godot's dialog when creating a new material. 🤔

It's potentially safer to use `.material` instead of `.tres` but maybe its type could be checked and a proper error returned if it's not really a material.

**Comment by RomualdDub** [comment]
My bad, it works fine with ".material" files ! Thank you :)

**Comment by codecat** [comment]
I'm gonna keep this issue open because I do wanna look into supporting the `.tres` extension as well 😄

**Comment by RomualdDub** [comment]
I figured out we can convert .tres to .material using the Save button in Godot :)
